from pathlib import Path

root = Path('.')
index = root / 'index.html'
app = root / 'app.js'
base_css = root / 'ui-base.css'
mobile_css = root / 'mobile-ui-v2.css'
readme = root / 'README.md'

s = index.read_text()
s = s.replace('<div class="brand">🌱💀 UNGROW v0.0.1</div>\n            <h1 class="title">SOMCHAI<span>Roast Button</span></h1>', '<div class="brand">🌱💀 UNGROW v0.0.1</div>\n            <div class="character-selector" role="group" aria-label="เลือกตัวละครต้นไม้">\n              <button type="button" data-character-id="somchai" aria-pressed="true">SOMCHAI</button>\n              <button type="button" data-character-id="ploy" aria-pressed="false">PLOY</button>\n            </div>\n            <h1 class="title"><b data-character-name>SOMCHAI</b><span>Roast Button</span></h1>')
s = s.replace('<div class="plant-stage"><svg data-plant-svg viewBox="0 0 320 320" role="img" aria-label="SOMCHAI plant health illustration"></svg></div>', '<div class="plant-stage"><svg data-plant-svg data-character-plant-label viewBox="0 0 320 320" role="img" aria-label="SOMCHAI plant health illustration"></svg></div>', 1)
s = s.replace('<div class="stat-row"><span>Owner Skill</span><b>21%</b></div>\n                <div class="meter owner"><i style="width:21%"></i></div>', '<div class="stat-row"><span>Owner Skill</span><b data-owner-skill-value>21%</b></div>\n                <div class="meter owner"><i data-owner-skill-bar style="width:21%"></i></div>', 1)
s = s.replace('          <h1 class="mobile-title">SOMCHAI</h1>\n          <p class="mobile-meta">Snake Plant · Stoic Introvert</p>', '          <div class="character-selector mobile-character-selector" role="group" aria-label="เลือกตัวละครต้นไม้">\n            <button type="button" data-character-id="somchai" aria-pressed="true">SOMCHAI</button>\n            <button type="button" data-character-id="ploy" aria-pressed="false">PLOY</button>\n          </div>\n          <h1 class="mobile-title" data-character-name>SOMCHAI</h1>\n          <p class="mobile-meta" data-character-subtitle>Snake Plant · Stoic Introvert</p>')
s = s.replace('<section class="mobile-play" aria-label="SOMCHAI roast controls">', '<section class="mobile-play" data-character-section-label aria-label="SOMCHAI roast controls">')
s = s.replace('<div class="plant-stage"><svg data-plant-svg viewBox="0 0 320 320" role="img" aria-label="SOMCHAI plant health illustration"></svg></div>', '<div class="plant-stage"><svg data-plant-svg data-character-plant-label viewBox="0 0 320 320" role="img" aria-label="SOMCHAI plant health illustration"></svg></div>', 1)
s = s.replace('<div class="stat-row"><span>Owner Skill</span><b>21%</b></div>\n              <div class="meter owner"><i style="width:21%"></i></div>', '<div class="stat-row"><span>Owner Skill</span><b data-owner-skill-value>21%</b></div>\n              <div class="meter owner"><i data-owner-skill-bar style="width:21%"></i></div>', 1)
s = s.replace('ui-base.css?v=canvasfix2', 'ui-base.css?v=characters1').replace('desktop-ui.css?v=canvasfix2', 'desktop-ui.css?v=characters1').replace('mobile-ui-v2.css?v=canvasfix2', 'mobile-ui-v2.css?v=characters1').replace('export-card.css?v=canvasfix2', 'export-card.css?v=characters1')
s = s.replace('  <script src="plant-svg.js?v=canvasfix2"></script>\n  <script src="app.js?v=verticalflow1"></script>', '  <script src="plant-svg.js?v=characters1"></script>\n  <script src="ploy-svg.js?v=characters1"></script>\n  <script src="characters.js?v=characters1"></script>\n  <script src="app.js?v=characters1"></script>')
index.write_text(s)

s = app.read_text()
start = s.index('const roasts = [')
end = s.index('const desktopExportLab')
new_top = '''const characters = window.UngrowCharacters;\nconst plantRenderers = {\n  somchai: window.UngrowPlantSvg,\n  ploy: window.UngrowPloySvg\n};\n\nconst state = {\n  characterId: "somchai",\n  health: 89,\n  roastIndex: characters.somchai.roasts.length - 1\n};\n'''
s = s[:start] + new_top + s[end:]
s = s.replace('function currentRoast() { return roasts[state.roastIndex]; }\nfunction getCondition(health = state.health) { return conditions.find(item => health >= item.min) || conditions[conditions.length - 1]; }', '''function currentCharacter() { return characters[state.characterId] || characters.somchai; }\nfunction currentRoast() {\n  const roasts = currentCharacter().roasts;\n  return roasts[state.roastIndex % roasts.length];\n}\nfunction currentAward() {\n  const awards = currentCharacter().awardLines;\n  return awards[state.roastIndex % awards.length];\n}\nfunction currentPlantRenderer() { return plantRenderers[currentCharacter().rendererId] || plantRenderers.somchai; }\nfunction getCondition(health = state.health) {\n  const conditions = currentCharacter().conditions;\n  return conditions.find(item => health >= item.min) || conditions[conditions.length - 1];\n}''')
old_render = '''function renderUI() {\n  const condition = getCondition();\n  const healthText = `${state.health}%`;\n\n  qsa("[data-health-value]").forEach(el => { el.textContent = healthText; });\n  qsa("[data-health-slider]").forEach(el => { if (Number(el.value) !== state.health) el.value = state.health; });\n  qsa("[data-health-bar]").forEach(el => { el.style.width = healthText; el.style.background = condition.color; });\n  qsa("[data-condition-title]").forEach(el => { el.textContent = condition.title; el.style.color = condition.color; });\n  qsa("[data-condition-sub]").forEach(el => { el.textContent = condition.sub; });\n  qsa("[data-roast]").forEach(el => { el.textContent = `“${currentRoast()}”`; });\n  qsa("[data-plant-svg]").forEach(svg => window.UngrowPlantSvg.render(svg, state.health));\n\n  qsa("[data-export-summary]").forEach(el => { el.textContent = `Health ${healthText} · ${condition.title}`; });\n  if (activeExportLab && !activeExportLab.hidden) scheduleExportRender();\n}\n'''
new_render = '''function renderUI() {\n  const character = currentCharacter();\n  const condition = getCondition();\n  const renderer = currentPlantRenderer();\n  const healthText = `${state.health}%`;\n  const ownerSkillText = `${character.ownerSkill}%`;\n\n  qsa("[data-character-name]").forEach(el => { el.textContent = character.name; });\n  qsa("[data-character-subtitle]").forEach(el => { el.textContent = character.subtitle; });\n  qsa("[data-character-plant-label]").forEach(el => { el.setAttribute("aria-label", `${character.name} ${character.plant} health illustration`); });\n  qsa("[data-character-section-label]").forEach(el => { el.setAttribute("aria-label", `${character.name} roast controls`); });\n  qsa("[data-character-id]").forEach(button => {\n    const selected = button.dataset.characterId === character.id;\n    button.setAttribute("aria-pressed", String(selected));\n  });\n  qsa("[data-owner-skill-value]").forEach(el => { el.textContent = ownerSkillText; });\n  qsa("[data-owner-skill-bar]").forEach(el => { el.style.width = ownerSkillText; });\n  qsa("[data-health-value]").forEach(el => { el.textContent = healthText; });\n  qsa("[data-health-slider]").forEach(el => { if (Number(el.value) !== state.health) el.value = state.health; });\n  qsa("[data-health-bar]").forEach(el => { el.style.width = healthText; el.style.background = condition.color; });\n  qsa("[data-condition-title]").forEach(el => { el.textContent = condition.title; el.style.color = condition.color; });\n  qsa("[data-condition-sub]").forEach(el => { el.textContent = condition.sub; });\n  qsa("[data-roast]").forEach(el => { el.textContent = `“${currentRoast()}”`; });\n  qsa("[data-plant-svg]").forEach(svg => renderer.render(svg, state.health));\n\n  qsa("[data-export-summary]").forEach(el => { el.textContent = `${character.name} · Health ${healthText} · ${condition.title}`; });\n  if (activeExportLab && !activeExportLab.hidden) scheduleExportRender();\n}\n'''
if old_render not in s:
    raise SystemExit('render block not found')
s = s.replace(old_render, new_render)
s = s.replace('''function nextRoast() {\n  let next = state.roastIndex;\n  while (next === state.roastIndex && roasts.length > 1) next = Math.floor(Math.random() * roasts.length);\n  state.roastIndex = next;\n  renderUI();\n}\n''', '''function setCharacter(characterId) {\n  if (!characters[characterId] || characterId === state.characterId) return;\n  state.characterId = characterId;\n  state.roastIndex = Math.min(state.roastIndex, currentCharacter().roasts.length - 1);\n  latestExportBlob = null;\n  renderUI();\n}\n\nfunction nextRoast() {\n  const roasts = currentCharacter().roasts;\n  let next = state.roastIndex;\n  while (next === state.roastIndex && roasts.length > 1) next = Math.floor(Math.random() * roasts.length);\n  state.roastIndex = next;\n  renderUI();\n}\n''')
s = s.replace('''async function drawSvgPlant(ctx, x, y, width, height, health) {\n  const image = await svgToImage(window.UngrowPlantSvg.buildStandalone(health));\n  ctx.drawImage(image, x, y, width, height);\n}\n''', '''async function drawSvgPlant(ctx, x, y, width, height, health, renderer = currentPlantRenderer()) {\n  const image = await svgToImage(renderer.buildStandalone(health));\n  ctx.drawImage(image, x, y, width, height);\n}\n''')
s = s.replace('''  const condition = getCondition();\n  const health = state.health;\n  const roast = currentRoast();\n''', '''  const character = currentCharacter();\n  const renderer = currentPlantRenderer();\n  const condition = getCondition();\n  const health = state.health;\n  const roast = currentRoast();\n''', 1)
s = s.replace('ctx.fillText("SOMCHAI", 104, 218);', 'ctx.fillText(character.name, 104, 218);')
s = s.replace('ctx.fillText("Snake Plant · Stoic Introvert", 108, 263);', 'ctx.fillText(character.subtitle, 108, 263);')
s = s.replace('''  const plantX = 330;\n  const plantY = 286;\n  const plantSize = 420;\n''', '''  const { plantX, plantY, plantSize } = character.exportLayout;\n''')
s = s.replace('await drawSvgPlant(ctx, plantX, plantY, plantSize, plantSize, health);', 'await drawSvgPlant(ctx, plantX, plantY, plantSize, plantSize, health, renderer);')
s = s.replace('ctx.fillText("21%", 930, 946);', 'ctx.fillText(`${character.ownerSkill}%`, 930, 946);')
s = s.replace('roundRect(ctx, 144, 960, 165, 14, 7, "#c84b31");', 'roundRect(ctx, 144, 960, 786 * character.ownerSkill / 100, 14, 7, "#c84b31");')
s = s.replace('ctx.fillText("🏆 เจ้าของที่ต้นไม้ไม่เคยร้องขอ", 104, 1250);', 'ctx.fillText(`🏆 ${currentAward()}`, 104, 1250);')
s = s.replace('ctx.fillText("#Ungrow   #PlantRoast   #SnakePlant", 104, 1282);', 'ctx.fillText(character.hashtags.join("   "), 104, 1282);')
s = s.replace('''  const filename = `ungrow-somchai-health-${state.health}.png`;\n  const file = new File([latestExportBlob], filename, { type: "image/png" });\n\n  if (supportsFileShare()) {\n    try {\n      await navigator.share({ files: [file], title: "Ungrow — SOMCHAI", text: `SOMCHAI · Plant Health ${state.health}%` });\n''', '''  const character = currentCharacter();\n  const filename = `ungrow-${character.id}-health-${state.health}.png`;\n  const file = new File([latestExportBlob], filename, { type: "image/png" });\n\n  if (supportsFileShare()) {\n    try {\n      await navigator.share({ files: [file], title: `Ungrow — ${character.name}`, text: `${character.name} · Plant Health ${state.health}%` });\n''')
s = s.replace('qsa("[data-health-slider]").forEach(slider => slider.addEventListener("input", e => setHealth(e.target.value)));', 'qsa("[data-character-id]").forEach(button => button.addEventListener("click", () => setCharacter(button.dataset.characterId)));\nqsa("[data-health-slider]").forEach(slider => slider.addEventListener("input", e => setHealth(e.target.value)));')
app.write_text(s)

selector_css = '.character-selector{display:inline-flex;gap:4px;margin-top:14px;padding:4px;border:1px solid var(--line);border-radius:14px;background:#f5f0e6}.character-selector button{appearance:none;min-height:44px;border:0;border-radius:10px;padding:0 16px;background:transparent;color:var(--muted);font-weight:950;letter-spacing:.03em;cursor:pointer}.character-selector button[aria-pressed="true"]{background:var(--ink);color:var(--paper);box-shadow:0 2px 0 rgba(11,33,23,.2)}.desktop-copy .title b{display:block;font:inherit;letter-spacing:inherit}.character-selector button:focus-visible{outline:3px solid var(--gold);outline-offset:2px}'
s = base_css.read_text()
if '.character-selector{' not in s:
    base_css.write_text(s.rstrip() + '\n' + selector_css + '\n')
mobile_selector_css = '@media(max-width:767px){.mobile-character-selector{display:grid;grid-template-columns:1fr 1fr;width:100%;margin-top:12px}.mobile-character-selector button{width:100%;padding:0 12px}.mobile-title{margin-top:16px}}'
s = mobile_css.read_text()
if '.mobile-character-selector{' not in s:
    mobile_css.write_text(s.rstrip() + '\n' + mobile_selector_css + '\n')

s = readme.read_text()
s = s.replace('Ungrow is a deliberately ridiculous open-source experiment. The first character is **SOMCHAI the Snake Plant**, whose main responsibility is judging the owner.', 'Ungrow is a deliberately ridiculous open-source experiment starring **SOMCHAI the Snake Plant** and **PLOY the Peace Lily** — two plants with very different ways of judging their owner.')
s = s.replace('- 🐍 Health-reactive SOMCHAI SVG character\n', '- 🌱 Selectable SOMCHAI + PLOY characters with shared state/rendering\n- 🐍 Health-reactive SOMCHAI SVG character\n- 🤍 Health-reactive PLOY Peace Lily SVG character\n')
s = s.replace('Shared State\n  ├─ health\n  ├─ roast\n  └─ condition', 'Shared State\n  ├─ characterId\n  ├─ health\n  ├─ roast\n  └─ condition')
s = s.replace('while sharing the same state and `plant-svg.js` renderer.', 'while sharing the same character-aware state and rendering path.')
s = s.replace('plant-svg.js        # SOMCHAI SVG renderer + health states\napp.js              # Shared state, interactions, PNG/share logic', 'characters.js       # Shared SOMCHAI/PLOY character data\nplant-svg.js        # SOMCHAI SVG renderer + health states\nploy-svg.js         # PLOY Peace Lily SVG renderer + health states\napp.js              # Character-aware shared state, interactions, PNG/share logic')
s = s.replace('- Add a new SOMCHAI roast\n', '- Add a new SOMCHAI or PLOY roast\n')
s = s.replace('- `v0.0.2` — Character data model / easier community contributions\n- `v0.0.3` — Second plant character (only after people actually care)', '- `v0.0.2` — Shared character data model + PLOY Peace Lily ✅\n- `v0.0.3` — Third plant character / easier community contributions')
readme.write_text(s)
